name: CI

on:
  push:
  pull_request:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  PYTHON_VERSION: 3.10

jobs:
  check-format:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK v7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.100

      - name: Restore tool
        run: dotnet tool restore

      # If not formated files are found check will fail
      - name: Check format
        run: dotnet tool run dotnet-format -- --check

  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    needs: [check-format]
    strategy:
      fail-fast: false
      matrix:
        framework: [net5.0, net6.0, netcoreapp3.1]
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK v7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.100

      - name: Build VsTestRunner
        run: dotnet build ./VsTestRunner.sln --configuration=Release

      - name: Test VsTestRunner 
        run: dotnet test ./VsTestRunner.sln --no-build --configuration=Release

      - name: Test VsTestRunner
        run: dotnet msbuild ./VsTestRunner.sln t:SmokeTest p:Configuration=Release
